arb-dir: lib/l10n
template-arb-file: en.arb
output-dir: lib/gen/l10n
output-localization-file: app_localizations.dart
synthetic-package: false
nullable-getter: false
untranslated-messages-file: untranslated_messages.json
preferred-supported-locales: ["en"]
