name: tanami_capital
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  theme_tailor_annotation: ^3.0.1
  flutter_secure_storage: ^9.2.4
  riverpod_annotation:
  go_router: ^14.8.1
  flutter_svg: ^2.0.17
  equatable: ^2.0.7
  dartz: ^0.10.1
  local_auth: ^2.3.0
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  pretty_dio_logger: ^1.4.0
  queen_validators: ^1.0.1
  pinput: ^5.0.1
  syncfusion_flutter_charts: ^28.2.11
  flutter_cached_pdfview: ^0.4.3
  patrol: ^3.14.1
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  theme_tailor: ^3.0.1
  riverpod_generator: ^2.6.3
  go_router_builder: ^2.8.2
  flutter_gen_runner:
  mockito: ^5.4.2
  change_app_package_name: ^1.5.0

flutter_gen:
  output: lib/gen/assets # Optional (default: lib/gen/)

  integrations:
    image: true
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/jpg/
    - assets/png/
    - assets/fonts/
    - .env
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100

    - family: Oxygen
      fonts:
        - asset: assets/fonts/oxygen/Oxygen-Regular.ttf
        - asset: assets/fonts/oxygen/Oxygen-Bold.ttf
          weight: 700
        - asset: assets/fonts/oxygen/Oxygen-Light.ttf
          weight: 300
      

patrol:
  app_name: Tanami Capital
  app_id: com.tanami.app
  android:
    package_name: com.example.myapp
